import model.Device;
import model.EthernetAdapter;
import model.Monitor;

public class Main {
    public static void main(String[] args) {
        System.out.println();
        System.out.println("1. Device class:");
        System.out.println("--------------------------------------------");
        Device firstDevice = new Device("Samsung", 1200, "123456789");
        Device secondDevice = new Device("Huawei", 1300, "987633333");
        Device thirdDevice = new Device("LG", 1200, "3433456789");
        Device fourthDevice = secondDevice;
        System.out.println("firstDevice => " + firstDevice);
        System.out.println("secondDevice => " + secondDevice);
        System.out.println("thirdDevice => " + thirdDevice);
        System.out.println("fourthDevice => " + fourthDevice);
        System.out.println();
        System.out.println("firstDevice hashCode: " + firstDevice.hashCode());
        System.out.println("secondDevice hashCode: " + secondDevice.hashCode());
        System.out.println("thirdDevice hashCode: " + thirdDevice.hashCode());
        System.out.println("fourthDevice hashCode: " + fourthDevice.hashCode());
        System.out.println();
        System.out.println("firstDevice equals secondDevice: " + firstDevice.equals(secondDevice));
        System.out.println("firstDevice equals thirdDevice: " + firstDevice.equals(thirdDevice));
        System.out.println("firstDevice equals fourthDevice: " + firstDevice.equals(fourthDevice));
        System.out.println();
        System.out.println("secondDevice equals thirdDevice: " + secondDevice.equals(thirdDevice));
        System.out.println("secondDevice equals fourthDevice: " + secondDevice.equals(fourthDevice));
        System.out.println();
        System.out.println("thirdDevice equals fourthDevice: " + thirdDevice.equals(fourthDevice));
        System.out.println("--------------------------------------------");
        System.out.println();
        System.out.println("2. EthernetAdapter:");
        System.out.println("--------------------------------------------");
        EthernetAdapter firstEthernetAdapter = new EthernetAdapter("Intel", 55, "234567890", "xcz12345", 1200);
        EthernetAdapter secondEthernetAdapter = firstEthernetAdapter;
        EthernetAdapter thirdEthernetAdapter = new EthernetAdapter("Starlink", 75, "3465675643", "tryr4546", 1400);
        EthernetAdapter fourthEthernetAdapter = new EthernetAdapter("TP-Link", 61, "2345632322", "tttz12345", 1300);
        System.out.println();
        System.out.println("firstEthernetAdapter => " + firstEthernetAdapter);
        System.out.println("secondEthernetAdapter => " + secondEthernetAdapter);
        System.out.println("thirdEthernetAdapter => " + thirdEthernetAdapter);
        System.out.println("fourthEthernetAdapter => " + fourthEthernetAdapter);
        System.out.println();
        System.out.println("firstEthernetAdapter hashCode: " + firstEthernetAdapter.hashCode());
        System.out.println("secondEthernetAdapter hashCode: " + secondEthernetAdapter.hashCode());
        System.out.println("thirdEthernetAdapter hashCode: " + thirdEthernetAdapter.hashCode());
        System.out.println("fourthEthernetAdapter hashCode: " + fourthEthernetAdapter.hashCode());
        System.out.println();
        System.out.println("firstEthernetAdapter equals secondEthernetAdapter: " + firstEthernetAdapter.equals(secondEthernetAdapter));
        System.out.println("firstEthernetAdapter equals thirdEthernetAdapter: " + firstEthernetAdapter.equals(thirdEthernetAdapter));
        System.out.println("firstEthernetAdapter equals fourthEthernetAdapter: " + firstEthernetAdapter.equals(fourthEthernetAdapter));
        System.out.println();
        System.out.println("secondEthernetAdapter equals thirdEthernetAdapter: " + secondEthernetAdapter.equals(thirdEthernetAdapter));
        System.out.println("secondEthernetAdapter equals fourthEthernetAdapter: " + secondEthernetAdapter.equals(fourthEthernetAdapter));
        System.out.println();
        System.out.println("thirdEthernetAdapter equals fourthEthernetAdapter: " + thirdEthernetAdapter.equals(fourthDevice));
        System.out.println("--------------------------------------------");
        System.out.println();
        System.out.println("3. Monitor:");
        System.out.println("--------------------------------------------");
        Device firstMonitor = new Monitor("Apple", 215, "3456789012", 1800, 1600);
        Device secondMonitor = new Monitor("Samsung", 200, "4565475467", 2200, 1500);
        Device thirdMonitor = secondMonitor;
        Device fourthMonitor = new Monitor("LG", 310, "36684356546", 2000, 1300);
        System.out.println("firstMonitor => " + firstMonitor);
        System.out.println("secondMonitor => " + secondMonitor);
        System.out.println("thirdMonitor => " + thirdMonitor);
        System.out.println("fourthMonitor => " + fourthMonitor);
        System.out.println();
        System.out.println("firstMonitor hashCode: " + firstMonitor.hashCode());
        System.out.println("secondMonitor hashCode: " + secondMonitor.hashCode());
        System.out.println("thirdMonitor hashCode: " + thirdMonitor.hashCode());
        System.out.println("fourthMonitor hashCode: " + fourthMonitor.hashCode());
        System.out.println();
        System.out.println("firstMonitor equals secondMonitor: " + firstMonitor.equals(secondMonitor));
        System.out.println("firstMonitor equals thirdMonitor: " + firstMonitor.equals(thirdMonitor));
        System.out.println("firstMonitor equals fourthMonitor: " + firstDevice.equals(fourthMonitor));
        System.out.println();
        System.out.println("secondMonitor equals thirdMonitor: " + secondMonitor.equals(thirdMonitor));
        System.out.println("secondMonitor equals fourthMonitor: " + secondMonitor.equals(fourthMonitor));
        System.out.println();
        System.out.println("thirdDevice equals fourthMonitor: " + thirdDevice.equals(fourthMonitor));
        System.out.println("--------------------------------------------");

    }
}